<?php
function application_menu() {
  $items['application/generalcollegeapplication'] = array(
    'title' => t('General College Application'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('application_form_page1'),
    'access arguments' => array('access content'),
    'description' => t('General College Application'),
    'file' => 'application_page1.inc',
    'file path' => drupal_get_path('module', 'application'),
    'type' => MENU_NORMAL_ITEM,
  );
  $items['application/generalcollegeapplication2'] = array(
    'title' => t('General College Application - Academic Experience'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('application_form_page2'),
    'access arguments' => array('access content'),
    'description' => t('General College Application'),
    'file' => 'application_page2.inc',
    'file path' => drupal_get_path('module', 'application'),
    'type' => MENU_NORMAL_ITEM,
  );
  $items['application/generalcollegeapplication3'] = array(
    'title' => t('General College Application - Academic Plans'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('application_form_page3'),
    'access arguments' => array('access content'),
    'description' => t('General College Application'),
    'file' => 'application_page3.inc',
    'file path' => drupal_get_path('module', 'application'),
    'type' => MENU_NORMAL_ITEM,
  );
  $items['application/generalcollegeapplication4'] = array(
    'title' => t('General College Application - Statistical Data'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('application_form_page4'),
    'access arguments' => array('access content'),
    'description' => t('General College Application'),
    'file' => 'application_page4.inc',
    'file path' => drupal_get_path('module', 'application'),
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}
